server.port=56030
spring.application.name=config

spring.cloud.config.server.git.uri=file:///C:/Users/SOFT/Documents/projects/watch%20ads/services/cloud/CONFIGS/

eureka.client.region = default
eureka.client.registryFetchIntervalSeconds = 5
eureka.client.serviceUrl.defaultZone=http://localhost:56031/eureka/


