version: "3.9"
services:
  config:
    image: ngaie/cloud-config
    restart: always
    ports:
      - "56030:56030"  
    volumes:
      - ./CONFIGS:/opt/CONFIGS
    environment:
      EUREKA_HOST_ZONE: "http://discovery:56031"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:56030/actuator"]
      interval: 30s
      timeout: 30s
      retries: 3
  discovery:
    image: ngaie/cloud-discovery
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "56031:56031"
    environment:
      CONFIG_SERVER_URL: "http://config:56030"
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:56031/actuator"]
      interval: 60s
      timeout: 30s
      retries: 3  

  gateway:
    image: ngaie/cloud-gateway
    restart: always
    depends_on:
      discovery:
        condition: service_healthy
    ports:
      - "56032:56032"
    environment:
      CONFIG_SERVER_URL: "http://config:56030"
      EUREKA_HOST_ZONE: "http://discovery:56031"
      ZIPKIN_URL: "http://172.20.10.6:9411"
      EUREKA_HOST: "discovery"

networks:
  default:
    external: true
    name: campaign
